### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#102]
TODO
---
- [x] refactor: Separate Web UI codes from go template
- [x] refactor: Migrate Web UI codes to typescript
- [x] feat: Add `tags` field to enable a workflow to have arbitrary tags (ex: `- daily`)
- [x] feat: Improve Web UI design
- [x] feat: Add the ability to update task status with a mouse click on visual graph on Web UI
- [x] fix: Not to send mail notifications when a workflow is canceled not failed
- [x] fix: Not to expandEnv on config page on Web UI
- [x] feat: Add named parameters (ex: `params: "p1=x p2=y"`)
- [x] feat: Add `stdout` field that can write standard output to any file in a step definition
- [x] feat: Add search function for workflows using free text keyword
- [x] feat: Add sorting function to HTML tables on Web UI using `react-table`
- [x] feat: start/stop buttons on Workflow list page
- [ ] feat: sorting function for dashboard timechart
- [x] feat: filtering workflows by clicking a tag on table on Web UI
- [x] feat: Change `name` field to an optional field by using the file name as a default value
- [x] feat: Add `version` subcommand that shows the version (#127)
- [x] feat: Add function to pass variables from one step to another using `output` field in a step definition
- [x] feat: Add function to embed arbitrary script in a YAML file using the `script` field
- [x] fix: Fix the formatting issue of scheduler's log on Web UI
- [x] fix: Fix goreleaser config and Makefile to embed the correct version value (ex: 1.0.0) using `-ldflags`
- [x] fix: Fix release GitHub Action and remove web assets from the repository (`bundle.js` and font files)
- [x] docs: REST API interface
---
## Not sure
- [ ] feat: Add No-Code GUI for workflow edit
- [ ] feat: i18n for Web UI
- [ ] test: Add tests for frontend Web UI codes in `admin` directory
- [ ] test: Improve the test coverage to 90%
- [ ] test: Add `--race` option to test command
- [ ] test: Add tests for Goroutine leaks
- [ ] feat: Add `--repeat-until` option to `start` subcommand
- [ ] refactor: Context handling logics in `cmd`, `agent`, `scheduler`, and `unix` package.
- [ ] feat: Add `Until` option to `RepeatPolicy` field to enable to specify the end time of repetitive task
- [ ] feat: Ability to manage multiple instances from a single instance on Web UI using Rest API interface
- [ ] feat: Make the agent an importable package from 3rd party software
- [ ] feat: Scheduler daemon
- [ ] feat: RBAC user authentication functionalities
- [ ] feat: Workflow layering mechanism such as JobNet
- [ ] feat: Windows support
- [ ] feat: Docker container image

**Comment by yohamta** [comment]
Almost done

**Comment by kuerme** [comment]
please support windows
